prepare for 1.0 release
pixiv/three-vrm pull request #1047
Opened 2022-09-21 01:22 UTC by 0b5vr

### Description

Done these jobs preparing for 1.0 release:

- Loaders, it now supports both `1.0` and `1.0-beta`
- Samples: Replace `three-vrm-girl` with `VRM1_Constraint_Twist_Sample`
- Samples: Bump specVersion of extensions to `1.0`
- Docs, comments: update URLs

I will do the bump of three-vrm itself later (would not be included in this PR).

2022-09-21 05:38 UTC, ke456-png requested changes
サンプルモデルの瞳周りで問題がありそうです
Unity(UniVRM)でも再現済み

2022-09-21 05:49 UTC, ke456-png reviewed
1.0 beta => 1.0

2022-09-21 11:31 UTC, 0b5vr commented
サンプルモデルの修正を行いました @ https://github.com/pixiv/three-vrm/pull/1047/commits/c3df82361c5aae78d7657f31a126fb8b7c6c93e5

2022-09-22 02:07 UTC, ke456-png commented
修正を確認しました！
![image](https://user-images.githubusercontent.com/108649297/191642632-047aa4cc-2fcc-42fe-a198-004609985e98.png)

2022-09-22 02:08 UTC, ke456-png approved these changes
Thanks! 👍

2022-09-22 03:20 UTC, merged