Remove unnecessary vertices
pixiv/three-vrm pull request #880
Opened 2021-12-28 10:08 UTC by 0b5vr

Add a new utility function `VRMUtils.removeUnnecessaryVertices`.

This is to address the issue that morph textures consumes gigantic amount of VRAM.
See comments for more details.

I probably have to apply this also for the current v0.x stream.

See: mrdoob/three.js#23095

2021-12-28 10:11 UTC, 0b5vr commented
We can finally arm ourselves with r133 VTF morph targets. Shoutouts to perfect sync community

2022-01-06 03:14 UTC, nyamadan requested changes
typoだけ修正提案させていただきました。

2022-01-06 03:14 UTC, nyamadan commented on packages/three-vrm/src/VRMUtils/removeUnnecessaryVertices.ts
> +        throw new Error('removeUnnecessaryVertices: InterlavedBufferAttribute is not supported');
```suggestion
        throw new Error('removeUnnecessaryVertices: InterleavedBufferAttribute is not supported');
```

typoのようです。

2022-01-06 03:14 UTC, nyamadan commented on packages/three-vrm/src/VRMUtils/removeUnnecessaryVertices.ts
> +        const originalIndex = originalIndexArray[i];
メモ

この処理でindexの最大値が減る。そのため各種attributeの大きさを減る。

2022-01-06 03:14 UTC, nyamadan commented on packages/three-vrm/src/VRMUtils/removeUnnecessaryVertices.ts
> +          throw new Error('removeUnnecessaryVertices: InterlavedBufferAttribute is not supported');
```suggestion
          throw new Error('removeUnnecessaryVertices: InterleavedBufferAttribute is not supported');
```

同様にtypoのようです。

2022-01-06 09:45 UTC, 0b5vr commented
@nyamadan https://github.com/mrdoob/three.js/blob/daaec2c91fe923f4394172b92b2ae9264c9321ec/src/renderers/webgl/WebGLMorphtargets.js#L36

2022-01-06 09:48 UTC, nyamadan approved these changes
LGTM

2022-01-06 09:59 UTC, merged